---
qbittorrent_enabled: false
qbittorrent_available_externally: false

# directories
qbittorrent_config_directory: "{{ docker_home }}/qbittorrent/config"
qbittorrent_download_directory: "{{ downloads_root }}"
qbittorrent_download_directory_active: "{{ downloads_root }}/.incomplete"

# uid / gid
qbittorrent_user_id: "1000"
qbittorrent_group_id: "1000"

# network
qbittorrent_port_http: "8701"
qbittorrent_hostname: "qbittorrent"

# docker
qbittorrent_container_name: "qbittorrent"
qbittorrent_image_name: "lscr.io/linuxserver/qbittorrent"
qbittorrent_image_version: "latest"

# specs
qbittorrent_memory: 1g
