---
- name: Start qBittorrent
  block:
    - name: Create qBittorrent Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ qbittorrent_config_directory }}"
        - "{{ qbittorrent_download_directory }}"
        - "{{ qbittorrent_download_directory_active }}"

    - name: Create qBittorrent Docker Container
      community.docker.docker_container:
        name: "{{ qbittorrent_container_name }}"
        image: "{{ qbittorrent_image_name }}:{{ qbittorrent_image_version }}"
        pull: true
        volumes:
          - "{{ qbittorrent_download_directory }}:/data:rw"
          - "{{ qbittorrent_config_directory }}:/config:rw"
          - "{{ torrents_root }}:/torrents:rw"
        ports:
          - "{{ qbittorrent_port_http }}:{{ qbittorrent_port_http }}"
        env:
          TZ: "{{ ansible_nas_timezone }}"
          PUID: "{{ qbittorrent_user_id }}"
          PGID: "{{ qbittorrent_group_id }}"
          WEBUI_PORT: "{{ qbittorrent_port_http }}"
          WEBUI_ADDRESS: "0.0.0.0"
          WEBUI_EXTERNAL_ACCESS: "true"          
        restart_policy: unless-stopped
        memory: "{{ qbittorrent_memory }}"
        labels:
          traefik.enable: "{{ qbittorrent_available_externally | string }}"
          traefik.http.routers.utorrent.rule: "Host(`{{ qbittorrent_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.utorrent.tls.certresolver: "letsencrypt"
          traefik.http.routers.utorrent.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.utorrent.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.utorrent.loadbalancer.server.port: "8080"
          homepage.group: Download Tools
          homepage.name: qBittorrent
          homepage.icon: qBittorrent
          homepage.href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ qbittorrent_port_http }}"

  when: qbittorrent_enabled is true

- name: Stop qBittorrent
  block:
    - name: Stop qBittorrent
      community.docker.docker_container:
        name: "{{ qbittorrent_container_name }}"
        state: absent
  when: qbittorrent_enabled is false
